start_one_time_mowing:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: lawn_mower
    runtime:
      required: false
      default: 60
      selector:
        number:
          min: 0
          max: 120
          step: 1
          unit_of_measurement: min
          mode: slider
    edge_cut:
      required: false
      default: false
      selector:
        boolean:
    zones:
      required: false
      example:
        - 1
        - 2
      selector:
        object:
